# Generated by Django 5.1.7 on 2025-03-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmissionanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizsubmissionanswer',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='quizsubmissionanswer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option'),
        ),
    ]
