# Generated by Django 5.1.7 on 2025-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quizsubmissionanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSubmissionAnswer',
        ),
    ]
